---
dockerfile_path: './jenkins-docker-config'
job_name: 'ci-pipeline-template'

download_node: 'https://nodejs.org/dist/'
node_version: 'v6.10.2'
node_package_name: "node-{{ node_version }}-linux-x64"
node_archive: "{{ node_package_name }}.tar.xz"

git_url: 'git@github.com:carlosfrias/test-ci.git'
git_name: 'carlosfrias'
git_branch: '*/master'
scm_polling_interval: '* * * * *'
jenkins_version: '2.32.2'

org: 'friasc'
username: 'friasc@google.com'
deployment_suffix: 'jenkins_deployment'
profile: 'test'
container_name: rccl_jenkins