---
- name: Build Jenkins Container
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
  - ~/.apigee/credentials.yml
  - jenkins-configuration.yml
  tasks:
  - name: Download node
    become: no
    get_url:
      url: "{{ download_node }}/{{ node_version }}/{{ node_archive }}"
      dest: "{{ docker_config_folder }}/{{ node_archive }}"

  - name: Download Maven
    become: no
    get_url:
      url: '{{ maven_download_url }}'
      dest: "{{ docker_config_folder }}/{{ maven_archive }}"

  - name: Copy Dockerfile to configure Jenkins instance
    template:
      src: ./templates/Dockerfile.j2
      dest: "{{ docker_config_folder }}/Dockerfile"

  - name: Create missing job-init folder
    file:
      path: "{{ docker_config_folder }}/jobs-init"
      state: directory

  - name: Copy pipeline job template
    template:
      src: ./templates/test-ci-pipeline.xml.j2
      dest: "{{ docker_config_folder }}/jobs-init/test-ci-pipeline.xml"

  - name: Copy maven config file
    template:
      src: ./templates/maven.groovy.j2
      dest: "{{ docker_config_folder }}/jenkins-init/maven.groovy"

  - name: Build Jenkins Image
    docker_image:
      name: "{{ container_name }}"
      state: present
      rm: true
      path: "{{ docker_config_folder }}"
