---
- name: Build Jenkins server
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
  - jenkins-configuration.yml
  tasks:
  - name: Install modules
    pip:
      name: "{{ item }}"
      state: present
    with_items:
    - docker-py

  - name: Obtain ssh credentials
    fetch:
      src: ~/.ssh/{{ item }}
      dest: "{{ dockerfile_path }}/ssh/{{ item }}"
      flat: yes
    with_items:
    - id_rsa
    - id_rsa.pub
    - known_hosts

- name: Clear a running instance and old images
  include: jenkins-docker-teardown.yml

- name: Build Jenkins Container
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
  - ~/.apigee/credentials.yml
  - jenkins-configuration.yml
  vars:

  tasks:
  - name: Download node
    become: no
    get_url:
      url: "{{ download_node }}/{{ node_version }}/{{ node_archive }}"
      dest: "{{ dockerfile_path }}/{{ node_archive }}"

  - name: Download Maven
    become: no
    get_url:
      url: '{{ maven_download_url }}'
      dest: "{{ dockerfile_path }}/{{ maven_archive }}"

  - name: Copy Dockerfile to configure Jenkins instance
    template:
      src: ./templates/Dockerfile.j2
      dest: "{{ dockerfile_path }}/Dockerfile"

  - name: Create missing job-init folder
    file:
      path: "{{ dockerfile_path }}/jobs-init"
      state: directory

  - name: Copy pipeline job template
    template:
      src: ./templates/test-ci-pipeline.xml.j2
      dest: "{{ dockerfile_path }}/jobs-init/test-ci-pipeline.xml"

  - name: Build Jenkins Image
    docker_image:
      name: "{{ container_name }}"
      state: present
      rm: true
      path: "{{ dockerfile_path }}"

  - name: Run Jenkins Container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name | default(container_name) }}"
      recreate: yes
      restart: yes
      force_kill: yes
      ports:
      - "8080:8080"
      env:
        GIT_NAME: "{{ git_name }}"
        GIT_EMAIL: "{{ git_email }}"
        GIT_PASSWORD: "{{ git_password }}"

  - name: Wait for Jenkins to startup
    wait_for:
      timeout: 30

- name: Retrieve initial admin password
  include: jenkins-docker-initial-password.yml
