---
- name: Run Jenkins Container
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
  - ~/.apigee/credentials.yml
  - jenkins-configuration.yml
  tasks:
  - name: Run Jenkins Container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name | default(container_name) }}"
      recreate: yes
      restart: yes
      force_kill: yes
      ports:
      - "8080:8080"
      env:
        GIT_NAME: "{{ git_name }}"
        GIT_EMAIL: "{{ git_email }}"
        GIT_PASSWORD: "{{ git_password }}"

  - name: Wait for Jenkins to startup
    wait_for:
      timeout: 30
