---
- name: Retrieve Jenkins Initial Admin Password
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
  - jenkins-configuration.yml
  tasks:
  - name: Retrieve initial admin password
    ignore_errors: yes
    command: "docker exec -i {{ container_name }} cat /var/jenkins_home/secrets/initialAdminPassword"
    register: jenkins_password

  - name: Print jenkins password
    ignore_errors: yes
    debug:
      msg: "Jenkins Initial Admin Password: {{ jenkins_password }}"

