---
- name: Retrieve Jenkins Initial Admin Password
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Retrieve initial admin password
    command: "docker exec -i {{ container_name }} cat /var/jenkins_home/secrets/initialAdminPassword"
    register: jenkins_password

  - name: Print jenkins password
    debug:
      msg: "Jenkins Initial Admin Password: {{ jenkins_password }}"

