---
- name: Build Jenkins server
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Install modules
    pip:
      name: "{{ item }}"
      state: present
    with_items:
    - docker-py

  - name: Obtain ssh credentials
    fetch:
      src: ~/.ssh/{{ item }}
      dest: docker/ssh/{{ item }}
      flat: yes
    with_items:
    - id_rsa
    - id_rsa.pub

- name: Clear a running instance and old images
  include: jenkins-teardown.yml

- name: Build Jenkins Container
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Build Jenkins Image
    docker_image:
      name: "{{ container_name }}"
      state: present
      path: ./docker

  - name: Run Jenkins Container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name | default(container_name) }}"
      recreate: yes
      restart: yes
      force_kill: yes
      ports:
      - "8080:8080"

  - name: Wait for Jenkins to startup
    wait_for:
      timeout: 30

- name: Retrieve initial admin password
  include: jenkins-initial-admin-password.yml
