---
- name: Run Jenkins Container
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
  - ~/.apigee/credentials.yml
  - jenkins-configuration.yml
  tasks:
  - name: Run Jenkins Container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ container_name }}"
      state: started
      recreate: yes
      keep_volumes: yes
      ports:
      - "8080:8080"
      env:
        GIT_NAME: "{{ git_name }}"
        GIT_SECRET_TOKEN: "{{ github_personal_token }}"
      volumes:
      - "/var/jenkins_home"

  - name: Wait for Jenkins to startup
    wait_for:
      timeout: 30
