---
docker_config_folder: './jenkins-docker-config'
job_name: 'ci-pipeline-template'

download_node: 'https://nodejs.org/dist/'
node_version: 'v6.10.2'
node_package_name: "node-{{ node_version }}-linux-x64"
node_archive: "{{ node_package_name }}.tar.xz"

#maven_version: 3.5.0
maven_version: 3.3.9
maven_download_url: http://www-eu.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
maven_package_name: "apache-maven-{{ maven_version }}"
maven_archive: "{{ maven_package_name }}-bin.tar.gz"

#git_url: 'git@github.com:carlosfrias/test-ci.git'
git_url: 'git@bitbucket.org:royal-digital/apigeetest1.git'
#git_name: 'carlosfrias'
git_name: 'friasc'
git_branch: '*/master'
scm_polling_interval: '* * * * *'
jenkins_version: '2.32.2'

org: 'friasc'
username: 'friasc@google.com'
deployment_suffix: 'jenkins_deployment'
profile: 'test'
container_name: rccl_jenkins
