FROM jenkins:{{ jenkins_version }}
MAINTAINER Carlos Frias <friasc@google.com>

VOLUME /var/jenkins_home

ENV MAVEN_HOME=/usr/share/maven/apache-maven-{{ maven_version }} \
    PATH="$PATH:$MAVEN_HOME/bin" \
    PATH="$PATH:/var/jenkins_home/apps/node-v6.10.2-linux-x64/bin"

ADD node-v6.10.2-linux-x64.tar.xz /var/jenkins_home/apps/
ADD apache-maven-{{ maven_version }}-bin.tar.gz /usr/share/maven

USER root
RUN apt-get update -y \
  && apt-get install -y tree git vim

COPY ssh/ /usr/share/jenkins/ref/.ssh
COPY ./jenkins-init/jenkins_plugins.txt /usr/share/jenkins/ref
COPY ./jenkins-init/init.groovy /usr/share/jenkins/ref/init.groovy
COPY ./jenkins-init/credentials.groovy /usr/share/jenkins/ref/plugin_config/stringCredentials.groovy
COPY ./jenkins-init/maven.groovy /usr/share/jenkins/ref/plugin_config/maven.groovy
COPY ./jenkins-init/nodejs.groovy /usr/share/jenkins/ref/plugin_config/nodejs.groovy
COPY ./jenkins-init/gitScm.groovy /usr/share/jenkins/ref/plugin_config/gitScm.groovy
COPY ./jobs-init/test-ci-pipeline.xml /usr/share/jenkins/ref/jobs/{{ job_name }}/config.xml

RUN /bin/chmod 0400 /usr/share/jenkins/ref/.ssh/id_rsa \
  && /bin/chmod 0400 /usr/share/jenkins/ref/.ssh/id_rsa.pub \
  && /bin/chmod 0544 /usr/share/jenkins/ref/.ssh/known_hosts \
  && /bin/chown jenkins:jenkins /usr/share/jenkins/ref/.ssh/id_rsa \
  && /bin/chown jenkins:jenkins /usr/share/jenkins/ref/.ssh/id_rsa.pub \
  && /bin/chown jenkins:jenkins /usr/share/jenkins/ref/jenkins_plugins.txt \
  && /bin/chown jenkins:jenkins /usr/share/jenkins/ref/init.groovy \
  && /bin/chown jenkins:jenkins /usr/share/jenkins/ref/plugin_config/stringCredentials.groovy \
  && /bin/chown jenkins:jenkins /usr/share/jenkins/ref/plugin_config/maven.groovy \
  && /bin/chown jenkins:jenkins /usr/share/jenkins/ref/plugin_config/nodejs.groovy \
  && /bin/chown jenkins:jenkins /usr/share/jenkins/ref/plugin_config/gitScm.groovy \
  && /bin/chown jenkins:jenkins /usr/share/jenkins/ref/jobs/{{ job_name }}/config.xml

RUN ln -s /var/jenkins_home/apps/node-v6.10.2-linux-x64/bin/node /usr/bin/node \
  && ln -s /var/jenkins_home/apps/node-v6.10.2-linux-x64/bin/npm /usr/bin/npm \
  && ln -s /usr/share/maven/apache-maven-{{ maven_version }}/bin/mvn /usr/bin/mvn \
  && /bin/chown -R jenkins:jenkins /var/jenkins_home \
  && /bin/chown -R jenkins:jenkins /var/jenkins_home/apps

USER jenkins
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/jenkins_plugins.txt
